# Generated by Django 5.0.3 on 2025-01-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Cooking_Time', models.CharField(max_length=30)),
                ('Servings', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=300)),
                ('Image', models.ImageField(default='', upload_to='images')),
                ('Ingrediants', models.CharField(max_length=300)),
                ('Instructions', models.TextField(max_length=300)),
                ('Category', models.CharField(blank=True, choices=[('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Salad', 'Salad'), ('Cold-Drinks', 'Cold-Drinks'), ('Easy', 'Easy')], max_length=50, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
