# Generated by Django 5.0.3 on 2025-02-26 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_recepie_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepie',
            name='price',
        ),
        migrations.AlterField(
            model_name='recepie',
            name='Cooking_Time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='Servings',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='Title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
