# Generated by Django 5.0.3 on 2025-12-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_remove_recepie_price_alter_recepie_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepie',
            name='Cooking_Time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='Servings',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='Title',
            field=models.CharField(max_length=30),
        ),
    ]
